variable "environment" {
  description = "Environment name"
  type        = string
  default     = "staging"
}

variable "bastion_ami" {
  description = "AMI ID for bastion host"
  type        = string
}

variable "bastion_instance_type" {
  description = "Instance type for bastion host"
  type        = string
  default     = "t2.micro"
}

variable "bastion_subnet_id" {
  description = "Subnet ID for bastion host"
  type        = string
}

variable "bastion_sg_id" {
  description = "Security group ID for bastion host"
  type        = string
}

variable "key_name" {
  description = "EC2 Key Pair name (not used, key generated by Terraform)"
  type        = string
  default     = "terraform-generated-key"
}
